version: "3"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    links:
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongodb:27018/MetroNZ"

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
